#---------------------------------------------------------------------#
#                               Draw.io                               #
#---------------------------------------------------------------------#
name: drawio

services:
  drawio:
    image: nickfedor/drawio
    container_name: drawio
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.drawio.rule=Host(`drawio.nickfedor.dev`)
      - traefik.http.routers.drawio.entrypoints=https
      - traefik.http.routers.drawio.tls=true
      - traefik.http.routers.drawio.tls.certresolver=cloudflare
      - traefik.http.services.drawio.loadbalancer.server.port=8080
      - traefik.http.routers.drawio.middlewares=authentik@file

networks:
  proxy:
    external: true
