#---------------------------------------------------------------------#
#                          VSCode Server                             #
#---------------------------------------------------------------------#
name: code-server

services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    hostname: code-server
    restart: unless-stopped
    volumes:
      - ./data/local:/home/coder/.local:rw
      - ./data/config:/home/coder/.config:rw
      - ~/Apps:/home/coder/Apps:rw
    environment:
      - DOCKER_USER=$USER
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.code-server.rule=Host(`code.nickfedor.dev`)
      - traefik.http.routers.code-server.entrypoints=https
      - traefik.http.routers.code-server.tls=true
      - traefik.http.routers.code-server.tls.certresolver=cloudflare
      - traefik.http.services.code-server.loadbalancer.server.port=8080
      - traefik.http.routers.code-server.middlewares=authentik@file

networks:
  proxy:
    external: true
