#---------------------------------------------------------------------#
#                                  Gitea                              #
#---------------------------------------------------------------------#
name: gitea

networks:
  proxy:
    external: true

services:
  gitea:
    container_name: gitea
    image: gitea/gitea:1.22.2-rootless
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`gitea.nickfedor.dev`)
      - traefik.http.routers.gitea.entrypoints=https
      - traefik.http.routers.gitea.tls=true
      - traefik.http.routers.gitea.tls.certresolver=cloudflare
      - traefik.http.services.gitea.loadbalancer.gitea.port=3000
    networks:
      - proxy
    restart: unless-stopped
    ports:
      - 2222:2222
    volumes:
      - ./data:/var/lib/gitea
      - ./config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro