#---------------------------------------------------------------------#
#                                CyberChef                            #
#---------------------------------------------------------------------#
name: cyberchef

networks:
  proxy:
    external: true

services:
  cyberchef:
    container_name: cyberchef
    image: ghcr.io/gchq/cyberchef:10.19.2
    labels:
      - traefik.enable=true
      - traefik.http.routers.cyberchef.rule=Host(`cyberchef.nickfedor.dev`)
      - traefik.http.routers.cyberchef.entrypoints=https
      - traefik.http.routers.cyberchef.service=cyberchef
      - traefik.http.services.cyberchef.loadbalancer.server.port=80
      - traefik.http.routers.cyberchef.tls=true
      - traefik.http.routers.cyberchef.tls.certresolver=cloudflare
      - traefik.http.routers.cyberchef.middlewares=authentik@file
    networks:
      - proxy
    restart: unless-stopped