#---------------------------------------------------------------------#
#                                 Homarr                              #
#---------------------------------------------------------------------#
name: homarr

services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:0.15.4
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/configs:/app/data/configs
      - ./data/icons:/app/public/icons
      - ./data/database:/data
    environment:
      - BASE_URL=homarr.nickfedor.dev
      - DEFAULT_COLOR_SCHEME=dark
      - TZ=America/Phoenix
      - DISABLE_ANALYTICS=true
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.homarr.rule=Host(`homarr.nickfedor.dev`)
      - traefik.http.routers.homarr.entrypoints=https
      - traefik.http.routers.homarr.tls=true
      - traefik.http.routers.homarr.tls.certresolver=cloudflare
      - traefik.http.routers.homarr.service=homarr
      - traefik.http.services.homarr.loadbalancer.server.port=7575
      - traefik.http.routers.homarr.middlewares=authentik@file

networks:
  proxy:
    external: true
