#---------------------------------------------------------------------#
#                            Go Playground                            #
#---------------------------------------------------------------------#
name: go-playground

services:
  go-playground:
    container_name: go-playground
    image: ghcr.io/x1unix/go-playground/go-playground:latest
    restart: unless-stopped
    environment:
      - APP_PLAYGROUND_URL=https://play.golang.org
      - APP_GOTIP_URL=https://gotipplay.golang.org
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.go-playground.rule=Host(`go-playground.nickfedor.dev`)
      - traefik.http.routers.go-playground.entrypoints=https
      - traefik.http.routers.go-playground.tls=true
      - traefik.http.routers.go-playground.tls.certresolver=cloudflare
      - traefik.http.routers.go-playground.service=go-playground
      - traefik.http.services.go-playground.loadbalancer.server.port=8000
      - traefik.http.routers.go-playground.middlewares=authentik@file

networks:
  proxy:
    external: true
