#---------------------------------------------------------------------#
#                             Apt-Cacher-ng                           #
#---------------------------------------------------------------------#
name: apt-cacher-ng

networks:
  proxy:
    external: true

services:
  apt-cacher-ng:
    container_name: apt-cacher-ng
    image: nicholas-fedor/apt-cacher-ng
    labels:
      - traefik.enable=true
      - traefik.http.routers.apt-cacher-ng.rule=Host(`apt-cacher-ng.nickfedor.dev`)
      - traefik.http.routers.apt-cacher-ng.entrypoints=https
      - traefik.http.routers.apt-cacher-ng.tls=true
      - traefik.http.services.apt-cacher-ng.loadbalancer.server.port=3142
      - traefik.http.routers.apt-cacher-ng.middlewares=authentik@file
    networks:
      - proxy
    restart: always
    ports:
      - 3142:3142
    volumes:
      - ./data:/var/cache/apt-cacher-ng