#---------------------------------------------------------------------#
#                               Rclone                                #
#---------------------------------------------------------------------#
name: rclone

networks:
  proxy:
    external: true

services:
  rclone:
    container_name: rclone
    image: rclone/rclone:latest
    env_file:
      - .env
    command: ["rcd", "--rc-web-gui", "--rc-addr=0.0.0.0:5572", "--rc-web-gui-no-open-browser", "--rc-user=${gui_user}", "--rc-pass=${gui_password}"]
    # ports:
    #   - 5572:5572
    labels:
      - traefik.enable=true
      - traefik.http.routers.rclone.rule=Host(`rclone.nickfedor.dev`)
      - traefik.http.routers.rclone.entrypoints=https
      - traefik.http.routers.rclone.service=rclone
      - traefik.http.services.rclone.loadbalancer.server.port=5572
      - traefik.http.routers.rclone.tls=true
      - traefik.http.routers.rclone.tls.certresolver=cloudflare
      - traefik.http.routers.rclone.middlewares=authentik@file
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - ./isos:/data:rw
      - ./config:/config/rclone:rw