#---------------------------------------------------------------------#
#                                Calibre                              #
#---------------------------------------------------------------------#
name: calibre

services:
  calibre:
    # https://hub.docker.com/r/linuxserver/calibre
    image: linuxserver/calibre
    restart: unless-stopped
    container_name: calibre
    volumes:
      - ./data/calibre/config:/config
      - ./data/calibre/Books:/library
      - ./data/calibre/Downloads:/Downloads
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.calibre.rule=Host(`calibre.nickfedor.dev`)
      - traefik.http.routers.calibre.entrypoints=https
      - traefik.http.routers.calibre.service=calibre
      - traefik.http.services.calibre.loadbalancer.server.port=8080
      - traefik.http.routers.calibre.tls=true
      - traefik.http.routers.calibre.tls.certresolver=cloudflare
      - traefik.http.routers.calibre.middlewares=authentik@file

  calibre-web:
    # https://hub.docker.com/r/linuxserver/calibre-web
    image: linuxserver/calibre-web
    restart: unless-stopped
    container_name: calibre-web
    volumes:
      - ./data/calibre-web/config:/config
      - ./data/calibre/Books:/library
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.calibre-web.rule=Host(`calibre-web.nickfedor.dev`)
      - traefik.http.routers.calibre-web.entrypoints=https
      - traefik.http.routers.calibre-web.service=calibre-web
      - traefik.http.services.calibre-web.loadbalancer.server.port=8083
      - traefik.http.routers.calibre-web.tls=true
      - traefik.http.routers.calibre-web.tls.certresolver=cloudflare
      - traefik.http.routers.calibre-web.middlewares=authentik@file

networks:
  proxy:
    external: true
