#---------------------------------------------------------------------#
#                                Ghost                                #
#---------------------------------------------------------------------#
name: ghost

networks:
  proxy:
    external: true
  storage:
    external: false

services:
  ghost:
    container_name: ghost
    depends_on:
      - ghost-mysql
    env_file:
      - .env
    environment:
      - url=https://$HOST
      - database__client=mysql
      - database__connection__host=ghost-mysql
      - database__connection__user=root
      - database__connection__password=$MYSQL_ROOT_PASSWORD
      - database__connection__database=ghost
    image: ghost:latest
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.ghost.rule=Host(`$HOST`)
      - traefik.http.routers.ghost.entrypoints=https
      - traefik.http.routers.ghost.tls=true
      - traefik.http.routers.ghost.tls.certresolver=cloudflare
      - traefik.http.routers.ghost.service=ghost
      - traefik.http.services.ghost.loadbalancer.server.port=2368
      - traefik.http.routers.ghost.middlewares=ghost-chain@file
    networks:
      - proxy
      - storage
    restart: unless-stopped
    volumes:
      - ./data/content:/var/lib/ghost/content

  ghost-mysql:
    container_name: ghost-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    image: mysql:8.0
    networks:
      - storage
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql

volumes:
  database:
    driver: local