#---------------------------------------------------------------------#
#                          SearXNG                                    #
#---------------------------------------------------------------------#
name: searxng

networks:
  proxy:
    external: true

services:
  searxng:
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    container_name: searxng
    environment:
      - SEARXNG_BASE_URL=https://searxng.nickfedor.dev/
      - SEARXNG_PORT=8080
      - SEARXNG_IMAGE_PROXY=true
    image: searxng/searxng:latest
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.searxng.rule=Host(`searxng.nickfedor.dev`)
      - traefik.http.routers.searxng.entrypoints=https
      - traefik.http.routers.searxng.tls=true
      - traefik.http.routers.searxng.tls.certresolver=cloudflare
      - traefik.http.services.searxng.loadbalancer.server.port=8080
      - traefik.http.routers.searxng.middlewares=authentik@file
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      - proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./data/searxng:/etc/searxng:rw